services:
    oro_authorize_net.form.type.settings:
        class: Oro\Bundle\AuthorizeNetBundle\Form\Type\AuthorizeNetSettingsType
        arguments:
            - '@translator.default'
            - '@oro_security.form.data_transformer.factory.crypted_data'
            - '@oro_authorize_net.settings.card_type.provider'
            - '@oro_authorize_net.settings.payment_action.provider'
        tags:
            - { name: form.type }

    oro_authorize_net.form.type.credit_card:
        class: Oro\Bundle\AuthorizeNetBundle\Form\Type\CreditCardType
        tags:
            - { name: form.type, alias: oro_authorize_net_credit_card }

    oro_authorize_net.form.type.credit_card_expiration_date:
        class: Oro\Bundle\AuthorizeNetBundle\Form\Type\CreditCardExpirationDateType
        tags:
            - { name: form.type, alias: oro_authorize_net_credit_card_expiration_date }
